import {GardenLight, GardenDark} from '../assests/svgs/GardenSvg';
import {ToolsLight, ToolsDark} from '../assests/svgs/ToolsSvg';
import {GroundworkDark, GroundworkLight} from '../assests/svgs/GroundworkSvg';
const Images = {
  BackGround: {
    Bg1: require('../assests/images/bg1.png'),
    Bg2: require('../assests//images/newbg.png'),
    storybg1: require('../assests/images/story1.png'),
    storybg2: require('../assests/images/story2.png'),
    storybg3: require('../assests/images/story3.png'),
    story4: require('../assests/images/story4.png'),
    story5: require('../assests/images/story5.png'),
    blackbg: require('../assests/images/blackbg.png'),
    black: require('../assests/images/black.png'),
    greenbg: require('../assests/images/greenbg1.png'),
    wolfwoman1: require('../assests/images/WolfWoman.png'),
    wolfwoman2: require('../assests/images/wolfwoman2.png'),
    chuchuhuas: require('../assests/images/chuchuhuas.png'),
    BlueLotus: require('../assests/images/bluelotus.png'),
    BlueL: require('../assests/images/BlueL.png'),
    croped: require('../assests/images/Wolfcropped.png'),
    lageChuchu: require('../assests/images/largeChu.png'),
    larggeMushrom: require('../assests/images/largemushroom.png'),
    largerose: require('../assests/images/largerose.png'),
    rectanglebg: require('../assests/images/Rectangle.png'),
    nopath2: require('../assests/images/Nopath2.png'),
    rectangle2: require('../assests/images/rectangle2.png'),
    path1: require('../assests/images/path.png'),
    pathbg: require('../assests/images/bg.png'),
    backgroundHue: require('../assests/images/BackgroundHue.png'),
    bearman: require('../assests/images/bearman.png'),
    bearman2: require('../assests/images/bhalo2.png'),
    jaguarman: require('../assests/images/jaguarman.png'),
    jaguarman2: require('../assests/images/4.1a.png'),
    birdwomen: require('../assests/images/birdwomen.png'),
    birdwomen2: require('../assests/images/3.1a.png'),
    dolphinBeing: require('../assests/images/dolphinBeing.png'),
    dolphinBeing2: require('../assests/images/dolphin.1a.png'),
  },
  Logos: {
    logo1: require('../assests/images/logo.png'),
    hands: require('../assests/images/hands.png'),
    layer: require('../assests/images/Layer.png'),
    layer2: require('../assests/images/Layer2.png'),
    lotus: require('../assests/images/lotus.png'),
    greylog: require('../assests/images/greylogo.png'),
    greenlogo: require('../assests/images/greenlogo.png'),
    greenheart: require('../assests/images/greenheart.png'),
    greenicon1: require('../assests/images/greenicon1.png'),
    greenicon2: require('../assests/images/greenicon2.png'),
    payment: require('../assests/images/payments.png'),
    redleaf1: require('../assests/images/redleaf1.png'),
    redleaf2: require('../assests/images/redleaf2.png'),
    redleaf3: require('../assests/images/redleaf3.png'),
    redleaf4: require('../assests/images/redleaf4.png'),
    dolphin: require('../assests/images/imag5.png'),
    graph: require('../assests/images/graphp.png'),
  },
  Icons: {
    upload: require('../assests/images/upload.png'),
    envelop: require('../assests/images/envelop.png'),
    light: require('../assests/images/light.png'),
    circle: require('../assests/images/circle.png'),
    triangle: require('../assests/images/triangle.png'),
    bluee: require('../assests/images/bluee.png'),
    heart1: require('../assests/images/heart1.png'),
    small: require('../assests/images/small.png'),
    meIcon: require('../assests/images/meIcon.png'),
    meIconSmall: require('../assests/images/meIconSmall.png'),
    leaf: require('../assests/images/leaf.png'),
    gheart: require('../assests/images/gheart.png'),
    gpluse: require('../assests/images/gplus.png'),
    spiral: require('../assests/images/spiral.png'),
    star: require('../assests/images/star.png'),
    arrow: require('../assests/images/arrow.png'),
    playbtn: require('../assests/images/play.png'),
    envelop1: require('../assests/images/envelope.png'),
    card: require('../assests/images/card.png'),
    visa: require('../assests/images/visa.png'),
    badge: require('../assests/images/badge.png'),
    circleplus: require('../assests/images/circlePlus2.png'),
    gleaf: require('../assests/images/greenleaf.png'),
    blocks: require('../assests/images/blocks.png'),
    gdownload: require('../assests/images/gdownload.png'),
    up1: require('../assests/images/up2.png'),
    headphone: require('../assests/images/headohone.png'),
    notify: require('../assests/images/notify.png'),
    folder: require('../assests/images/folder.png'),
    logout: require('../assests/images/logout.png'),
    bars: require('../assests/images/bars.png'),
    person: require('../assests/images/person.png'),
    lock: require('../assests/images/lock.png'),
    video: require('../assests/images/video.png'),
    Pcircle: require('../assests/images/Pcircle.png'),
    prectangel: require('../assests/images/prectangle.png'),
    pinki: require('../assests/images/pinki.png'),
    sun: require('../assests/images/sun.png'),
    downloadgreen: require('../assests/images/greenarrow.png'),
    wsun: require('../assests/images/wsun.png'),
    wheart: require('../assests/images/wheartoutline.png'),
    wleafe: require('../assests/images/wleafe.png'),
    wcircle: require('../assests/images/wcircle.png'),
    waves: require('../assests/images/whitewaves.png'),
    wbox: require('../assests/images/whitebox.png'),
    wtrangle: require('../assests/images/wtriangle.png'),
    grenarrow: require('../assests/images/greenarrow.png'),
    wheartoutline: require('../assests/images/wheartoutline.png'),
    checkmarkCircle: require('../assests/images/checkmark-circle.png'),
  },
  Imgs: {
    pic1: require('../assests/images/pic1.png/'),
    bird: require('../assests/images/bird.png'),
    bear: require('../assests/images/Bear.png'),
    women: require('../assests/images/women.png'),
    jaguar: require('../assests/images/jaguar.png'),
    Rainbow: require('../assests/images/Rainbow.png'),
    lotus1: require('../assests/images/lotus1.png'),
    rose: require('../assests/images/rose.png'),
    rose1: require('../assests/images/rose1.png'),
    rose2: require('../assests/images/rose2.png'),
    rose3: require('../assests/images/rose3.png'),
    rose4: require('../assests/images/rose5.png'),
    mushrooms: require('../assests/images/mushrooms.png'),
    cuhuchuhuas1: require('../assests/images/chuchuhuas1.png'),
    chuchuhuasa: require('../assests/images/chuchhuas1.png'),
    cuhuchuhuasb: require('../assests/images/chuchuhuas2.png'),
    chuchuhuasc: require('../assests/images/chuchuhuas3.png'),
    lotusa: require('../assests/images/lotus1.png'),
    lotusb: require('../assests/images/lotusb.png'),
    lotusc: require('../assests/images/lotusc.png'),
    mushroomsa: require('../assests/images/mushroom1.png'),
    mushroomsb: require('../assests/images/mushroom2.png'),
    mushroomsc: require('../assests/images/mushrooms.png'),
    mushroomsd: require('../assests/images/mushrrom3.png'),
    startbg: require('../assests/images/bgstart.png'),
    R1: require('../assests/images/R1.png'),
    R2: require('../assests/images/R2.png'),
    R3: require('../assests/images/R3.png'),
    R4: require('../assests/images/R4.png'),
    nebula: require('../assests/images/Nebula.png'),
    pegasus: require('../assests/images/Pegasus.png'),
    user1: require('../assests/images/user1 35.png'),
    user2: require('../assests/images/user2.png'),
    smallblue1: require('../assests/images/smallblue1.png'),
    bluelotus: require('../assests/images/bluelotus.png'),
    lotusD: require('../assests/images/lotusd.png'),
    meetScreenIcon1: require('../assests/images/meetScreenIcon1.png'),
    meetScreenIcon2: require('../assests/images/meetScreenIcon2.png'),
    meetScreenIcon3: require('../assests/images/meetScreenIcon3.png'),
    meetScreenIcon4: require('../assests/images/meetScreenIcon4.png'),
    chuchuRose1: require('../assests/images/chuchuRose1.png'),
    chuchuRose2: require('../assests/images/chuchuRose2.png'),
    chuchuRose3: require('../assests/images/chuchuRose3.png'),
    chuchuRose4: require('../assests/images/chuchuRose4.png'),
    chuchuLotus1: require('../assests/images/chuchuLotus1.png'),
    chuchuLotus2: require('../assests/images/chuchuLotus2.png'),
    chuchuLotus3: require('../assests/images/chuchuLotus3.png'),
    chuchuLotus4: require('../assests/images/chuchuLotus4.png'),
    chuchuMushroom1: require('../assests/images/chuchuMushroom1.png'),
    chuchuMushroom2: require('../assests/images/chuchuMushroom2.png'),
    chuchuMushroom3: require('../assests/images/chuchuMushroom3.png'),
    chuchuMushroom4: require('../assests/images/chuchuMushroom4.png'),
    chuchuTree1: require('../assests/images/chuchuTree1.png'),
    chuchuTree2: require('../assests/images/chuchuTree2.png'),
    chuchuTree3: require('../assests/images/chuchuTree3.png'),
    chuchuTree4: require('../assests/images/chuchuTree4.png'),
    journeyIcon1: require('../assests/images/journeyIcon1.png'),
    journeyIcon2: require('../assests/images/journeyIcon2.png'),
    journeyIcon3: require('../assests/images/journeyIcon3.png'),
    journeyIcon4: require('../assests/images/journeyIcon4.png'),
    journeyIcon5: require('../assests/images/journeyIcon5.png'),
    blueLotusLarge: require('../assests/images/blueLotusLarge.png'),
    roseLarge: require('../assests/images/roseLarge.png'),
    mushroomLarge: require('../assests/images/mushroomLarge.png'),
    treeLarge: require('../assests/images/treeLarge.png'),
  },
  svgs: {
    gardenLight: <GardenLight />,
    gardenDark: <GardenDark />,
    toolsLight: <ToolsLight />,
    toolsDark: <ToolsDark />,
    groundworkLight: <GroundworkLight />,
    groundworkDark: <GroundworkDark />,
  },
};

export default Images;
